### ISSUE TITLE
Creating a new endpoint similar to the legacy portal.do

### ISSUE THREAD

**Issue by danielabutano** [intermine/redgenes#735]
In BG we need a portal endpoint similar to that one provided by the legacy interface.
It's used by the im registry, when is acting as a splash page to import from Galaxy to InterMine.
Data are sent using the method POST.
Here a code section from the im-registry
`function mineNavButton(mine, dataToTransfer) {
  return '<form action="' + mine.url + '/portal.do" name="list" method="post">' +
    '<input type="hidden" name="externalids" value="' +
    dataToTransfer.identifiers.join(",") + '" />' +
    '<input type="hidden" name="class" value="' +
    dataToTransfer.identifierType + '" />' +
    '<input type="submit" value="Send to ' + mine.name + '" />' +
    '</form>';
}`
The endpoint should accept also the optional extraValue (organism).
The new endopoint after checking the identifiers posted, redirect to the page below
![image](https://user-images.githubusercontent.com/1678179/124922176-2709d400-dff1-11eb-8dbd-e5c3f9e47fb4.png)

**Comment by danielabutano** [comment]
This might be used by pombase too to create list into pombemine

**Comment by danielabutano** [comment]
@uosl do you need more clarifications?

**Comment by heralden** [comment]
I have some questions. Can I drop the `/query/*.do` path or does it need to match the legacy API? I will only implement **List of identifiers** (https://intermine.readthedocs.io/en/latest/webapp/linking-in/#list-of-identifiers) right? (Same as in your issue description.)

I was thinking of using the same approach as https://github.com/intermine/bluegenes/pull/443 just adding an extra parameter (or path?) to identify the type of link, e.g. POST /link/region and POST /link/upload. I might have to include the mine name as well to handle BG covering multiple mines, so perhaps POST /pombemine link=upload. Otherwise I will use the same param names as before.

**Comment by danielabutano** [comment]
Hi @uosl, I think that it would be better if it matched with the legacy API, so we do no have to update the existing applications which use it (e.g the registry , when it send identifiers from galaxy to the mine instances).

**Comment by danielabutano** [comment]
The new endpoint in BG should received the input as described in the ticket and then implement the same process implemented in the Upload page, wne the user clicks the "Continue" button which I think is:

1. call the service/ids
2. wait for the status SUCCESS
3. calls service/ids/{idresolutionidentifier}/results
4. display the result in the page below:
![image](https://user-images.githubusercontent.com/1678179/151559529-0d5ecb43-cdd6-4bca-9d71-52882a9ed0f2.png)

**Comment by kimrutherford** [comment]
Hi.  Is POST supported for this endpoint?  Some of our list are quite long.  I tried with curl from the command line and got:

```
This POST request to /pombemine is not handled by the BlueGenes server, which is deployed to /. 
```

Thanks.

**Comment by heralden** [comment]
Sorry about that, it was an oversight to not include POST. We'll add this for the next release (https://github.com/intermine/bluegenes/issues/792). Thanks for letting us know.

**Comment by heralden** [comment]
@kimrutherford Turns out POST was supported, but HTTP response 302 was used instead of 303 (the latter ensures the request is redirected with GET instead of POST, although most clients always do that anyways for backwards compatibility). I've fixed this now in the coming v1.4.2 release so it should work correctly with more clients.

Just note that if you use `-X POST` with curl it will not work, as it overrides the 303 behaviour. You can use `-d ...` instead, or test with a regular html form:
```html
<form action="http://localhost:5000/pombemine/portal.do" method="post">
  <input type="hidden" name="externalids" value="smd3,smd1,cwf12,cwf2,cwf3,cwf4,cwf5,smd2,cwf11,sap145">
  <input type="hidden" name="class" value="Gene">
  <input type="submit" value="Submit">
</form>
```

Let me know if you still have issues.

**Comment by kimrutherford** [comment]
Thanks!  I'll give it a go.

**Comment by kimrutherford** [comment]
Hi @heralden.  Sorry the delay in testing.

I've been trying this URL: http://pombemine.rahtiapp.fi/pombemine/portal.do?externalids=SPAC1556.06&class=Gene

It look like it's partly working.  The lookup succeeds but the page doesn't render properly:

![pombemine-portaldo-1](https://user-images.githubusercontent.com/90474/169174568-5b90413c-c151-45b6-946b-a2fb72748138.png)

There are lots of errors in the console like:
```
Uncaught SyntaxError: Unexpected token '<' (at AjaxServices.js:1:1)
```
and
```
Uncaught ReferenceError: OtherMines is not defined
    at portal.do?externalids=SPAC1556.06&class=Gene:1030:9
```

I noticed that the FlyMine list example on this page has the same problem: http://intermine.org/im-docs/docs/4.0.0/webapp/linking-in/index/

http://www.flymine.org/query/portal.do?externalids=CG2262,CG3069,CG2859,CG5041,FBgn0036513&class=Gene

I tried a form with POST and got a blank page.  Here's the form:

```html
<form action="http://pombemine.rahtiapp.fi/pombemine/portal.do" method="post">
  <input type="hidden" name="externalids" value="smd3,smd1,cwf12,cwf2,cwf3,cwf4,cwf5,smd2,cwf11,sap145">
  <input type="hidden" name="class" value="Gene">
  <input type="submit" value="Submit">
</form>
```

The Chrome console has this error:
```
POST http://pombemine.rahtiapp.fi/pombemine/portal.do net::ERR_INCOMPLETE_CHUNKED_ENCODING 200
```

Do you have any advice?

Thanks.

**Comment by heralden** [comment]
@kimrutherford It looks like this is happening due to how the reverse proxy is setup. For flymine.org, it will work if you change *query* to *flymine* like so: http://www.flymine.org/flymine/portal.do?externalids=CG2262,CG3069,CG2859,CG5041,FBgn0036513&class=Gene

The reverse proxy is setup to facilitate some features of the old webapp, which isn't working in this case and overriding Bluegenes. We'll need to have a think on how we'll change the reverse proxy configuration.

For Pombemine we can probably safely remove the reverse proxy rule for `/portal.do`. I'll look into doing this later this week and it should fix the problem.

**Comment by heralden** [comment]
@kimrutherford I have updated the reverse proxy rules for pombemine and http://pombemine.rahtiapp.fi/pombemine/portal.do?externalids=SPAC1556.06&class=Gene is working now.
