### ISSUE TITLE
"Go by most popular queries" is empty when templates are unranked

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#805]
How does this field get configured? Or is it automatically populated based on the actual most popular queries

**Comment by heralden** [comment]
It is automatically populated: *The categories are the top 6 with the most numerous templates that are part of the top 50 ranked templates. The templates to each category are part of the same top 50 ranked templates, although reduced to the top 10 for each category.*

Unfortunately the hits from BG aren't counted yet (https://github.com/intermine/intermine/issues/2278). I see this leads to it being blank on Pombemine, which isn't good. Hope it's alright I'll repurpose this issue to fix that - it should still show templates even if they aren't ranked.

**Comment by heralden** [comment]
This is probably due to the templates having `"rank": "unranked"` instead of a number in the JSON.

https://github.com/intermine/bluegenes/blob/f627314f6befedad0a549812b406d61907c8276a/src/cljs/bluegenes/pages/templates/subs.cljs#L80

Should be an easy fix by adding a check for whether all templates are unranked and if so, just grab the first (up to) 50 templates.
