### ISSUE TITLE
When linking in to ID resolver, first object type is selected for saving list, regardless of class specified

### ISSUE THREAD

**Issue by ValWood** [intermine/redgenes#808]
I transferred a gene list from PomBase, and it appears just fine:

<img width="1219" alt="Screenshot 2022-05-31 at 17 20 37" src="https://user-images.githubusercontent.com/7359272/171224842-19e10bb1-2db2-4867-8438-36f0bea96822.png">

but when I rename it, it changes from "gene" to "allele" AND the list is now empty
<img width="1104" alt="Screenshot 2022-05-31 at 17 19 44" src="https://user-images.githubusercontent.com/7359272/171225091-46b2c212-f303-47d4-9fe4-a06edf621896.png">

**Comment by ValWood** [comment]
It is nothing to do with the renaming. It happens as soon as I try to save the imported list.

**Comment by ValWood** [comment]
CC @kimrutherford

**Comment by ValWood** [comment]
I see what the issue is here.

I now have the following classes added to the query starting points:
<img width="369" alt="Screenshot 2022-05-31 at 19 28 10" src="https://user-images.githubusercontent.com/7359272/171258934-23e39059-2534-49e5-bf12-0446accef493.png">

and when a query is sent from PomBAse I am not asked what type of list it is.  PombeMine is assuming that the list is an Allele list (presumably because it is at the top?)

I'm assuming this because when I upload a list I need to answer the question about list type.

**Comment by kimrutherford** [comment]
> and when a query is sent from PomBAse I am not asked what type of list it is. PombeMine is assuming that the list is an Allele list (presumably because it is at the top?)

The list is sent from PomBase as a Gene list.  Which is why it says something like "42 of your 42 identifiers matched a Gene" and the name in the box is something like "Gene list for all organisms 31 May 2022 18:56:33".

Maybe it's the save step where it's forgetting that it should be a Gene list.

@heralden @danielabutano we're passing "class=Gene" and "externalids=..." with POST.

It you'd like an example, use the "Export" menu at the top left here: https://www.pombase.org/results/from/id/e2518260-eff5-4e7b-9465-fb55347bded1

**Comment by heralden** [comment]
Thanks for reporting. This is a bad bug!
